# src/fast_openmdao/__init__.py

"""OpenMDAO integration layer for FAST-Python."""

from fast_openmdao.analysis import ConvergenceError, SourceWeightVector, WeightSum
from fast_openmdao.atmosphere import Gravity, StandardAtmosphere
from fast_openmdao.battery import (
    AvailableCellCapacity,
    BatteryChargeOCV,
    BatteryCyclingAging,
    BatteryCurrent,
    DetailedBatterySizing,
    BatteryPowerHistory,
    BatteryPowerStep,
    BatteryWeightFromEnergy,
)
from fast_openmdao.components import FastPythonComponent
from fast_openmdao.constraint import (
    CruiseDynamicPressure,
    FAR25ClimbConstraint,
    FAR25EngineGradient,
    JetAEOClimbConstraint,
    JetApproachConstraint,
    JetCeilingConstraint,
    JetCruiseConstraint,
    JetFAR25NamedClimbConstraint,
    JetLandingFieldLengthConstraint,
    JetTakeoffFieldLengthConstraint,
    OEIMultiplier,
    PsLossSigmoid,
)
from fast_openmdao.cost import BatteryReplacementCost
from fast_openmdao.engine import (
    AirIntegratedHeat,
    AirSpecificHeat,
    AirSpecificHeatVolume,
    AirTemperatureFromHeatAdded,
    AirTemperatureFromHeatRemoved,
    BurnerFlow,
    ChokedArea,
    CompressorStageFlow,
    DiffuserFlow,
    FlowArea,
    JetAIntegratedHeat,
    LocalEfficiency,
    LocalReynolds,
    MassFlowParameter,
    OffDesignNozzleMach,
    PerfectExpansionNozzleFlow,
    SimpleOffDesignTurbofan,
    StaticDensity,
    StaticPressure,
    StaticTemperature,
    ThermalPerfectGamma,
    TotalPressure,
    TotalTemperature,
    TurbineStageFlow,
    TurbofanLinearSizing,
    TurbopropLinearSizing,
)
from fast_openmdao.mission import (
    CruiseBreguetDetailedBattery,
    CruiseBreguetEfficiencyTriplet,
    CruiseBreguetPowerHistory,
    CruiseBreguetPowerSplit,
    CruiseBreguetPropulsiveEfficiency,
    CruiseBreguetSourceEnergy,
    CruiseTimeTargetDistance,
    FlightConditions,
    InitialEnergyRemaining,
)
from fast_openmdao.oew import NumericSum, TurbofanAirframeWeight, TurbopropAirframeWeight
from fast_openmdao.optimization import (
    BatteryEnergyAvailable,
    ElectricMotorPowerAvailable,
    FeasibleStep,
    OperationalObjective,
    OperationalSplitConstraints,
    PowerManagementObjective,
    PowerLimitConstraints,
)
from fast_openmdao.problem import make_fast_optimization_problem, make_fast_problem
from fast_openmdao.projection import (
    BatterySpecificEnergyProjection,
    ElectricMotorSpecificPowerProjection,
    KPPProjection,
)
from fast_openmdao.regression import GaussianProcessPrediction, SquaredExponentialKernel
from fast_openmdao.propulsion import (
    CableWeightForSizing,
    EngineLapse,
    EngineThrustRequirement,
    FuelUseHistory,
    ParallelHybridArchitecture,
    PowerAvailable,
    PowerFlow,
    PowerSupplementCheck,
    SafeComponentWeight,
    ThrustSinkEfficiency,
    TransmitterFanEfficiency,
    TurbopropEngineWeightForSizing,
)
from fast_openmdao.units import UnitConversion

__version__ = "0.1.0"

__all__ = [
    "AirIntegratedHeat",
    "AirSpecificHeat",
    "AirSpecificHeatVolume",
    "AirTemperatureFromHeatAdded",
    "AirTemperatureFromHeatRemoved",
    "BatteryEnergyAvailable",
    "BatteryChargeOCV",
    "BatteryCyclingAging",
    "BatteryReplacementCost",
    "BatterySpecificEnergyProjection",
    "AvailableCellCapacity",
    "BatteryCurrent",
    "DetailedBatterySizing",
    "BatteryPowerHistory",
    "BatteryPowerStep",
    "BatteryWeightFromEnergy",
    "BurnerFlow",
    "ChokedArea",
    "CableWeightForSizing",
    "CompressorStageFlow",
    "ConvergenceError",
    "DiffuserFlow",
    "CruiseDynamicPressure",
    "CruiseBreguetDetailedBattery",
    "CruiseBreguetEfficiencyTriplet",
    "CruiseBreguetPowerHistory",
    "CruiseBreguetPowerSplit",
    "CruiseBreguetPropulsiveEfficiency",
    "CruiseBreguetSourceEnergy",
    "CruiseTimeTargetDistance",
    "ElectricMotorSpecificPowerProjection",
    "ElectricMotorPowerAvailable",
    "FeasibleStep",
    "EngineLapse",
    "EngineThrustRequirement",
    "FAR25EngineGradient",
    "FAR25ClimbConstraint",
    "FastPythonComponent",
    "FlightConditions",
    "FlowArea",
    "FuelUseHistory",
    "Gravity",
    "GaussianProcessPrediction",
    "InitialEnergyRemaining",
    "JetAEOClimbConstraint",
    "JetApproachConstraint",
    "JetCeilingConstraint",
    "JetAIntegratedHeat",
    "JetCruiseConstraint",
    "JetFAR25NamedClimbConstraint",
    "JetLandingFieldLengthConstraint",
    "JetTakeoffFieldLengthConstraint",
    "KPPProjection",
    "LocalEfficiency",
    "LocalReynolds",
    "MassFlowParameter",
    "NumericSum",
    "OEIMultiplier",
    "OffDesignNozzleMach",
    "PerfectExpansionNozzleFlow",
    "ParallelHybridArchitecture",
    "OperationalObjective",
    "OperationalSplitConstraints",
    "PowerManagementObjective",
    "PowerLimitConstraints",
    "PowerAvailable",
    "PowerFlow",
    "PowerSupplementCheck",
    "PsLossSigmoid",
    "SafeComponentWeight",
    "SimpleOffDesignTurbofan",
    "SourceWeightVector",
    "StaticDensity",
    "StaticPressure",
    "StaticTemperature",
    "StandardAtmosphere",
    "SquaredExponentialKernel",
    "ThermalPerfectGamma",
    "TotalPressure",
    "TotalTemperature",
    "TurbineStageFlow",
    "TurbofanLinearSizing",
    "TurbopropLinearSizing",
    "ThrustSinkEfficiency",
    "TransmitterFanEfficiency",
    "TurbopropEngineWeightForSizing",
    "TurbopropAirframeWeight",
    "TurbofanAirframeWeight",
    "UnitConversion",
    "WeightSum",
    "__version__",
    "make_fast_optimization_problem",
    "make_fast_problem",
]
